const dataArr = [
{ pre:""  , txt:"Ibrahim Mazzawi"},
{ pre:""  , txt:"+Ms. Unknown"},
{ pre:"sB"  , txt:"Khalil Mazzawi  Ibrahim"},
{ pre:"sL"  , txt:"+Hanneh Zahlawy"},
{ pre:"sLsB"  , txt:"Nasser Mazzawi"},
{ pre:"sLsL"  , txt:"+Saadah Ayoub Zaher"},
{ pre:"sLsLsB"  , txt:"Moussa Mazzawi"},
{ pre:"sLsLsB"  , txt:"Khalil Mazzawi"},
{ pre:"sLsLsL"  , txt:"+Afifeh Touma"},
{ pre:"sLsLsLsB"  , txt:"Mariam Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Abdullah Mazzawi"},
{ pre:"sLsLsLsL"  , txt:"+Martha Muhanna"},
{ pre:"sLsLsLsLsB"  , txt:"Anisseh Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Abdou Mazzawi"},
{ pre:"sLsLsLsL"  , txt:"+Martha Muhanna ( El Makdah)"},
{ pre:"sLsLsLsLsB"  , txt:"Khalil Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Mounira Mazzawi  Salim"},
{ pre:"sLsLsLsLsLsB"  , txt:"Nawal Mazzawi Khalil I"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Elias Shahin"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Rawia Shahin"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Sanaa Shahin"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Ramy Shahin"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Sarry Shahin"},
{ pre:"sLsLsLsLsLsB"  , txt:"Abdou Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Nadia Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Khalil Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Suha Srouji Yousef"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Nada Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Abdou Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Nassim Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Sisil Simaan  Louis"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Leen Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Sama Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Nour Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Shereen Mazzawi"},
{ pre:"sLsLsLsLsLsLss"  , txt:"+Samir Srouji Yousef"},
{ pre:"sLsLsLsLsLsLsssB"  , txt:"Layal Srouji"},
{ pre:"sLsLsLsLsLsLsssB"  , txt:"Tamer Srouji"},
{ pre:"sLsLsLsLsLsLsssB"  , txt:"Jude Srouji"},
{ pre:"sLsLsLsLsLsB"  , txt:"Amal Mazzawi Khalil II"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Atef Saed  Issa"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Manar Saed  Atef"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Issa Saed Atef"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Hazar Saed  Atef"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Ehab Saed  Atef"},
{ pre:"sLsLsLsLsLsB"  , txt:"Antoine Mazzawi I"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Siham Yousef Banna I"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Luna Mazzawi I"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Kameel Khoury Nicola"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"May Khoury Kameel"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Lara Mazzawi II"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Hadi Mazzawi I"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Joe Mazzawi I"},
{ pre:"sLsLsLsLsLsB"  , txt:"Antoinette Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Victor Irsheid"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Ghada Irsheid  Victor"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Jules Irsheid Victor"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Rania Irsheid  Victor"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Areen Irsheid  Victor"},
{ pre:"sLsLsLsLsLsB"  , txt:"Nasser Mazzawi III"},
{ pre:"sLsLsLsLsLss"  , txt:"+Nadera Arab Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Nisreen Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Nirmeen Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Huda Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Moeen Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Betty Khoury"},
{ pre:"sLsLsLsLsLsB"  , txt:"Majed Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Lilian Khoury Elie"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Moeen Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Marwan Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Mario Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Muna Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Mounir Mazzawi"},
{ pre:"sLsLsLsLsLss"  , txt:"+Julianne Arthur Newman"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Martha Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Malek Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Max (Mounir ) Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Julliette Mazzawi Abdou"},
{ pre:"sLsLsLsLsB"  , txt:"Emil Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Farideh Mazzawi"},
{ pre:"sLsLsB"  , txt:"Hanneh Mazzawi"},
{ pre:"sLsLsB"  , txt:"Hanna Mazzawi"},
{ pre:"sLsLsL"  , txt:"+Latifeh Mazzawi Assad"},
{ pre:"sLsLsLsB"  , txt:"Amineh Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Ameen Mazzawi"},
{ pre:"sLsLsLsL"  , txt:"+Jameeleh Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Nazirah Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Hanna Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Samira Ashkar Radwan"},
{ pre:"sLsLsLsLsLsB"  , txt:"Ameen Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Reem Abu Hannah Emil"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Ola Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Dima Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Hanna Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Alaa Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Edward Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Ketty Totary  Zakariya"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Husam Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Basel Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Feras Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Ramzi Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Hanan Tabar Saied"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Munder Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Elias Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Jowel Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Shadia Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Mazen Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Sanaa Ashkar Bassem"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"George Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Estefan Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Jean Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Mariam Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Ausama Mazzawi"},
{ pre:"sLsLsLsLsLss"  , txt:"+Denise Helou Tony"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Raghad Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Noor Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Ward Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Afaf Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Lotof Mazzawi"},
{ pre:"sLsLsLsLss"  , txt:"+Ms. Unknown"},
{ pre:"sLsLsLsLsssB"  , txt:"Yuseph Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Jameleh Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Josephine Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Jumana Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Janan Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Jameel Mazzawi"},
{ pre:"sLsLsLsL"  , txt:"+Muntaha Ghanim"},
{ pre:"sLsLsLsLsB"  , txt:"Latifeh Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Raja Mazzawi"},
{ pre:"sLsLsLsLss"  , txt:"+Blanche Totari Elias"},
{ pre:"sLsLsLsLsssB"  , txt:"Jameel Mazzawi"},
{ pre:"sLsLsLsLsssL"  , txt:"+Rula Nasr Josef"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Sama Mazzawi"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Juna Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Shadi Mazzawi"},
{ pre:"sLsLsLsLsssL"  , txt:"+Lana Copty Nabih"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Nadeem Mazzawi"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Fares Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Nibal Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Nabeel Mazzawi"},
{ pre:"sLsLsLsLssss"  , txt:"+Rawan Kahaz Raja"},
{ pre:"sLsLsLsLsssssB"  , txt:"Yareen Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Jamileh Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Saleemeh Mazzawi"},
{ pre:"sLsLsB"  , txt:"Warde Mazzawi  Nasser"},
{ pre:"sLsB"  , txt:"Sleiman Mazzawi"},
{ pre:"sLsL"  , txt:"+Mariam Srouji  Hanna"},
{ pre:"sLsLsB"  , txt:"Asaad Mazzawi"},
{ pre:"sLsLsL"  , txt:"+1)ghantuseh Zaher 2)sarah Abu Aun"},
{ pre:"sLsLsLsB"  , txt:"Mikhaeel Mazzawi"},
{ pre:"sLsLsLsL"  , txt:"+1)hajaleh Mazzawi Saleh 2)fairuz Farsun Hanna"},
{ pre:"sLsLsLsLsB"  , txt:"Nayfeh Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Keysar Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Naheel Zaher  Assad"},
{ pre:"sLsLsLsLsLsB"  , txt:"Michel Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Nadia Banna Hanna"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Nahla Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Cezar Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+1)rando Abayah Victor 2)---------Farah"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Nadia Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Niveen Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Mary Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Michel Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Zuher Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Amal Mazzawi Mussa"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Wael Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Majd Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Sawsan Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Suheil Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Nayef Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Alice Abu Nassar Mikhael"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Samia Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Suheila Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Maha Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Fouad Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Shiraz Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Nayef Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Sami Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Mouna Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Victor Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Elias Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Jihan Sruji Najib"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Andre Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Kameel Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Gaby Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Amal Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Rachel Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Sami Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Jannette Karram Jamil"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Manal Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Shiraz Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Jorjina Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Maurice Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Jannette Mazzawi  Nimer"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Wafaa Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Elias Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Katy Marjieh  Sami"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Maurice Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Narmin Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Nasim Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Tony Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Ghayda Warwar"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Jannet Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Jowel Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Christeen Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Anis Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Suheila Bisharat Khalil"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Marwan Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Mona Deeb Michel"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Anis Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"June Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Shadan Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Rev. Munir Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Marina Francis Yacoub"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Sharbel Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Fadi Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Elyanus Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Reem Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Ranaa Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Ramiz Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Qeysar Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Afaf Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Asaad Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Samira Khalil Abbud"},
{ pre:"sLsLsLsLsLsB"  , txt:"Linda Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Yousef Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Berta(Bernadette) Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Albert Mazzawi"},
{ pre:"sLsLsLsLsLss"  , txt:"+Suheila Damouni Salim"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Maysaa Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Asaad Mazzawi"},
{ pre:"sLsLsLsLsLsssL"  , txt:"+Rula Tabba Metri"},
{ pre:"sLsLsLsLsLsssLsB"  , txt:"Nicole Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Joseph Mazzawi"},
{ pre:"sLsLsLsLsLsssL"  , txt:"+Rima Noufi Sameeh"},
{ pre:"sLsLsLsLsLsssLsB"  , txt:"Maria Mazzawi"},
{ pre:"sLsLsLsLsLsssLsB"  , txt:"Maya Mazzawi"},
{ pre:"sLsLsLsLsLsssLsB"  , txt:"Tamar Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Mulham Mazzawi"},
{ pre:"sLsLsLsLsLssss"  , txt:"+Shereen Khoury Ibrahim"},
{ pre:"sLsLsLsLsLsssssB"  , txt:"Basel Mazzawi"},
{ pre:"sLsLsLsLsLsssssB"  , txt:"Tamer Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Najdiyeh Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Wasef Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Basmeh Mazzawi Shibly"},
{ pre:"sLsLsLsLsLsB"  , txt:"Hajaleh Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Aydah Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Nadia Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Asad Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Silvia Rashed Farah"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Areen Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Wasef Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Layla Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Violette Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Ibrahim Mazzawi"},
{ pre:"sLsLsLsLsLss"  , txt:"+Lina Zaatre Munjid"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Awni Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Lilyan Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Basma Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Basel Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Yusra Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Wadeaah Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Wadie Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Therez Mikhaeel Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Mikhaeel Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Amal Victor Awees"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Wadie Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Reem Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Mays Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Mufeed Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Rojena Fahed Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Thereza Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Elias Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Christeen Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Yuseph Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Fairouz Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Hanan Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Moeen Mazzawi"},
{ pre:"sLsLsLsLsLss"  , txt:"+Areej Fehmi Abu Dahud"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Fadi Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Naef Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Afifi Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Latifeh Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Salim Mazzawi"},
{ pre:"sLsLsLsL"  , txt:"+1)marta Elias Yunes 2)adla Elias Yunes"},
{ pre:"sLsLsLsLsB"  , txt:"Bandar Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Naeem Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Ramzieh Younes"},
{ pre:"sLsLsLsLsLsB"  , txt:"Rosette Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Aydah Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Salim Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Burbara Jaraisy"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Naeem Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Ola Jarjoura Aqueel"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Ms. Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Rana Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Rami Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Basilious Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Suheil Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Nawal Abbud Yuseph"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Amal Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Ola Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Elias Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Fares Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Nadia Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Samia Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Samir Mazzawi"},
{ pre:"sLsLsLsLsLss"  , txt:"+Suheir Marjiyeh Muhsen"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Reem Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Majdi (Leon) Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Elia Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Marcelle Mazzawi  Naoum"},
{ pre:"sLsLsLsLsLsB"  , txt:"Claudette Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Adla (Addoulah) Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Nabil Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Ikhlas Sweis"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Nadine Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Elie Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Elian Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Ramzi Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Olama Elias Bakhit"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Reda Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Manar Khoury Lutfi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Ramzi Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Ramez Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Marcelle Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Tarek Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Randa Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Mounir Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Madelein Alfred Mondo"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Ziyad Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Adel Mazzawi"},
{ pre:"sLsLsLsLsLss"  , txt:"+Dina Elias Bakhit"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Elia Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Tamara Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Tamer Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Marie Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Rashid Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+1)anyes  Jon2)???3)joice Unknown"},
{ pre:"sLsLsLsLsLsB"  , txt:"Saleem Mazzawi"},
{ pre:"sLsLsLsLsLss"  , txt:"+Ms. Unknown"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Mary Anne Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Mounira Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"George Mazzawi"},
{ pre:"sLsLsLsLss"  , txt:"+Margueritte Mazzawi Naoum"},
{ pre:"sLsLsLsLsssB"  , txt:"Victor Mazzawi"},
{ pre:"sLsLsLsLsssL"  , txt:"+Hala Sami Sabty"},
{ pre:"sLsLsLsLsssLsB"  , txt:"George Mazzawi"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Dina Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Fayez Mazzawi"},
{ pre:"sLsLsLsLsssL"  , txt:"+Vivian Masri  Edwar"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Kareem Mazzawi"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Majeed Mazzawi"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Patrick Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Amira Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Suheila Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Sleiman Mazzawi"},
{ pre:"sLsLsLsL"  , txt:"+Farideh Mazzawi Khalil"},
{ pre:"sLsLsLsLsB"  , txt:"Tawfik Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Fairouz Mabjish Elias"},
{ pre:"sLsLsLsLsLsB"  , txt:"Sleiman Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Farideh Mazzawi Raja"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Elham Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Tawfik Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Amer Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Raghida Simaan Tannous"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Ameer Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Rawi Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Anan Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Victor Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Soumaya Mazzawi Zidan"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Vera Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Lubna Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Yuseph Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Jeryes Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+May Mazzawi  Zidan"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Janette Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Lina Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Yakoub Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Leena Indrya Suheil"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Nataly Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Juleen Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Elias Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Farid Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Evette Totary Muneer"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Arij Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Fady Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Anayat Marjiyeh Faheem"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Kareena Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Farid Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Nisreen Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Feras Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Ms. Unknown"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Majd Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Areen Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Nabeeh Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Hanan Rizek Naji"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Rami Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Ruba Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Razan Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Adnan Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Amira Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Afifi Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Abla Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Mary Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Elias Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Julliette Abu-Salem Endrawus"},
{ pre:"sLsLsLsLsLsB"  , txt:"Wasfi Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Kamilia Totary Anis"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Ola Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Rula Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Reem Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Elias Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Ratib Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Juliette Khalil Jammal"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Maria Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Rina Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Joseph Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Awni Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Nadia Mazzawi  Aziz"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Essam Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Nahi Helou  Farid"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Awni Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Anan Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Amal Sabbagh Zuheir"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Tala Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Emad Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Zuheir Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Nabila Jammal Khalil"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Vivian Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Katy Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Ramy Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Azmi Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Siham Mazzawi Jamal"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Jiryes Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Eman Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Zahi Mazzawi"},
{ pre:"sLsLsLsLsLss"  , txt:"+Ruwayda Abu Sinni Nimer"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Einas Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Bshara Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Elia Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Raja Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Mary Sibani Tawfik 2/Samira Abu Nuwara Elias Samira Abu Nuwara Elias"},
{ pre:"sLsLsLsLsLsB"  , txt:"Farideh Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Marwan Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Salam Mazzawi Anton"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Raja Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Colette Nawattha Nazih"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Marwan Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Hala Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Rawand Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Ramez Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Munzer Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Lilian Ben Saadun Hayem"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Mary Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Ron Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Fatina Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Maysoun Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Majed Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Rose Musallam George"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"John Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Andrew Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Mazen Mazzawi"},
{ pre:"sLsLsLsLsLss"  , txt:"+Kari Jesper Robberstad"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Tina Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Samir Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Rami Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Yusra Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Fairuz Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Mansour Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Said Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Anton Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Nabiha Sibani  Tawfik"},
{ pre:"sLsLsLsLsLsB"  , txt:"Salam Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Samia Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Maha Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Mary Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Ghassan Mazzawi"},
{ pre:"sLsLsLsLsLss"  , txt:"+Hanan Sruji Michel"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Tony Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Ameer Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Aziz Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Nawal Helou Nadim"},
{ pre:"sLsLsLsLsLsB"  , txt:"Diana Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Nadia Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Rimon Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Jumanah Khamis Jeries"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Aziz Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Adi Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Maysam Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Ghasoub Mazzawi"},
{ pre:"sLsLsLsLsLss"  , txt:"+Areej Copty Fouad"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Basel Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Nawal Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Jamal Mazzawi"},
{ pre:"sLsLsLsLss"  , txt:"+Ellen Abu Salem  Indrawes"},
{ pre:"sLsLsLsLsssB"  , txt:"Hani Mazzawi"},
{ pre:"sLsLsLsLsssL"  , txt:"+Amal Badaan  Tannous"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Leena Mazzawi"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Randa Mazzawi"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Rania Mazzawi"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Jumana Mazzawi"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Jamal Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Amal Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Eva Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Mounir Mazzawi"},
{ pre:"sLsLsLsLsssL"  , txt:"+Sawsan Farran Joseph"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Reema Mazzawi"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Feras Mazzawi"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Elen Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Siham Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Thouria Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Iskandar Mazzawi"},
{ pre:"sLsLsLss"  , txt:"+Wardeh Mazzawi Dahoud"},
{ pre:"sLsLsLsssB"  , txt:"Zhour Mazzawi"},
{ pre:"sLsLsLsssB"  , txt:"Asaad Mazzawi"},
{ pre:"sLsLsLsssB"  , txt:"Munder Mazzawi"},
{ pre:"sLsLsLsssL"  , txt:"+Sarah Farraj"},
{ pre:"sLsLsLsssLsB"  , txt:"Iskandar Mazzawi"},
{ pre:"sLsLsLsssLsB"  , txt:"Naseem Mazzawi"},
{ pre:"sLsLsLsssB"  , txt:"Marguerite Mazzawi"},
{ pre:"sLsLsLsssB"  , txt:"Yvonne Mazzawi"},
{ pre:"sLsLsLsssB"  , txt:"Therese Mazzawi"},
{ pre:"sLsLsLsssB"  , txt:"Evette Mazzawi"},
{ pre:"sLsLsLsssB"  , txt:"Siham Mazzawi"},
{ pre:"sLsLsLsssB"  , txt:"Jehan Mazzawi"},
{ pre:"sLsLsB"  , txt:"Yousef Mazzawi"},
{ pre:"sLsLsL"  , txt:"+Wardeh Hadad Yakoub"},
{ pre:"sLsLsLsB"  , txt:"Adlah Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Hana Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Niemeh Mazzawi"},
{ pre:"sLsLsLsL"  , txt:"+Mary Jarro"},
{ pre:"sLsLsLsLsB"  , txt:"Tawfik Mazzawi"},
{ pre:"sLsLsLsLss"  , txt:"+Thuraya Abu Saed Elias"},
{ pre:"sLsLsLsLsssB"  , txt:"Subhiyeh Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Mineem Mazzawi"},
{ pre:"sLsLsLsL"  , txt:"+Nayfeh Mansour Assaad"},
{ pre:"sLsLsLsLsB"  , txt:"Yousef Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Ms. Unknown"},
{ pre:"sLsLsLsLsLsB"  , txt:"Hupert Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Ms. Unknown"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Michel Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Mark Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Mathew Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Mike Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Peter Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Maggy Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Joanna Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Mitchelli Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Nieman Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Ablah Copty"},
{ pre:"sLsLsLsLsLsB"  , txt:"Niva Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Mineem Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Ms. Unknown"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Nieman Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Mark Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Steven Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Tawfik Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Ms. Unknown"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Shadi Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Nicolas Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Jawdat Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Louis Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Michel Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Jean Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Marcelle Tubia"},
{ pre:"sLsLsLsLsLsB"  , txt:"Maha Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Salim Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Nihaya Abu Rahme Elias"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Jean Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Naji Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Nael Mazzawi"},
{ pre:"sLsLsLsLsLss"  , txt:"+Muna Akkawi Fahed"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Fares Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Ameer Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Rose Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Naoum Mazzawi"},
{ pre:"sLsLsLsL"  , txt:"+Thouria Mazzawi Asaad  Sleiman"},
{ pre:"sLsLsLsLsB"  , txt:"Alfred (Farid) Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Angele Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Marguerite Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Solange Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Albert Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Alice Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Mary Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"George Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Rose Hajjar"},
{ pre:"sLsLsLsLsLsB"  , txt:"Kamal Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Suraya Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Layla Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Marcelle Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Francois Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Niaman Mazzawi"},
{ pre:"sLsLsB"  , txt:"Nasrah Mazzawi"},
{ pre:"sLsLsB"  , txt:"Hilweh Mazzawi"},
{ pre:"sLsB"  , txt:"Abdullah Mazzawi"},
{ pre:"sLsL"  , txt:"+Sofia Azzam Mhesen"},
{ pre:"sLsLsB"  , txt:"Saleh Mazzawi"},
{ pre:"sLsLsL"  , txt:"+Rojina Mansour Abdalla"},
{ pre:"sLsLsLsB"  , txt:"Shibly Mazzawi"},
{ pre:"sLsLsLsL"  , txt:"+1) Labibeh Karam 2) Mateel Mazzawi Moussa"},
{ pre:"sLsLsLsLsB"  , txt:"Hind Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Subhi Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Saleh Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Georgette Mazzawi  Najib"},
{ pre:"sLsLsLsLsLsB"  , txt:"Hanna Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Izees Abu Rahmon"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Georgina Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Narmeen Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Fairuz Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Labibeh Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Hani Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Ghada Banna Essa"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Saleh Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Yuseph Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Hanna Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Agnes Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Isabelle Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Basmeh Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Bassem Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Manerva Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Shibly Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Edwar (Edy) Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Cedar Dahoud  Maurice"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Manerva Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Bassem Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Mary Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Mirna Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"George Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Nabeela Saleeba"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Ranin Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Tamer Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Rany Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Lily Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Randa Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Reem Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Marie Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Mazzawi Mazzawi"},
{ pre:"sLsLsLsLss"  , txt:"+Margo Dahdal"},
{ pre:"sLsLsLsLsssB"  , txt:"Rimon Mazzawi"},
{ pre:"sLsLsLsLsssL"  , txt:"+Hala Sabeeh Qupty"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Mazzawi Mazzawi"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Izees Mazzawi"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Mariana Mazzawi"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Nataly Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Mounir Mazzawi"},
{ pre:"sLsLsLsLsssL"  , txt:"+Sawsan Aboud  Lotof"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Rimonda Mazzawi"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Margarit Mazzawi"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Maroun Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Rimonda Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Hajaleh Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Hana Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Radi Mazzawi"},
{ pre:"sLsLsLsL"  , txt:"+Yamameh Dardas"},
{ pre:"sLsLsLsLsB"  , txt:"Salem Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Hajaleh Nicola Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Rose Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Ruda Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Ramzyeh Karam Rashid"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Salem Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Hala Laham Ibrahim"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Ramzieh Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Ruda Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Amer Mazzawi"},
{ pre:"sLsLsLsLsLsLss"  , txt:"+Awham Jiries Mussa"},
{ pre:"sLsLsLsLsLsLsssB"  , txt:"Hiba Mazzawi"},
{ pre:"sLsLsLsLsLsLsssB"  , txt:"Hanin Mazzawi"},
{ pre:"sLsLsLsLsLsLsssB"  , txt:"Haya Mazzawi"},
{ pre:"sLsLsLsLsLsLsssB"  , txt:"Yasmina Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Fawzi Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Lourees Hayek Yussef"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Nader Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Bader Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Rana Jadon Joseph"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Habib Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Wiliam Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Carmen Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Andera Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Hael Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Marwan Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Claire Khoury Jeryes"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Lorees Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Rony Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Lana Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Rozan Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Malak Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Nael Nazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Maher Mazzawi"},
{ pre:"sLsLsLsLsLsLss"  , txt:"+Reena Muklashi Anwar"},
{ pre:"sLsLsLsLsLsLsssB"  , txt:"Yamen Mazzawi"},
{ pre:"sLsLsLsLsLsLsssB"  , txt:"Ady Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"William Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Ibrahim Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Rose Fallash Iskandar"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Jules Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Nadin Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Jean Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Camelia Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Saleemeh Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Mikhaeel Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Rojina Nicola Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Fahed Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Camilia Sruji Tannous"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Rojina Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Randa Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Dina Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Mikhaeel Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Vera Mazzawi Victor"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Fahed Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Waseem Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Leen Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Wissam Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Ablah Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Therese Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Afaf Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Salam Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Salwa Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Ghassan Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Fatina Haddad Yusef"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Ghasoub Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Katreen Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Layla Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Neeme Mazzawi"},
{ pre:"sLsLsLsLsLss"  , txt:"+Feryal Zaatre Munjid"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Joseph Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Fadi Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Ranin Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Maarouf Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+1)louiza Murani Khalil 2)mary Khalil Bshara"},
{ pre:"sLsLsLsLsLsB"  , txt:"Janette Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Nahi Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Hani Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Rudayna Mazzawi  Abdallah"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Katy Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Marouf Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Haifa Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Emtaness Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Raji Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+1) Amira Jubran 2)adeil Moussa Fouad"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Maroun Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Katarzyna Karczewska"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Miriam Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Mirvat Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Mariana Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Maisa Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Sharbel Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Lama Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Suha Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Amira Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Wafa Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Elie Mazzawi"},
{ pre:"sLsLsLsLsLss"  , txt:"+Ezdehar Indraous Youssef"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Julia Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Fadi Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Juwana Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Jeyana Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"George Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Simaan Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Mary Mazzawi  Shibly"},
{ pre:"sLsLsLsLsLsB"  , txt:"Rene Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Suheil Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Rudi Ashkar Salim"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Simon Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Christeen Najjar William"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Leen Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Samir Mazzawi"},
{ pre:"sLsLsLsLsLsLss"  , txt:"+Mona Kardosh Anwar"},
{ pre:"sLsLsLsLsLsLsssB"  , txt:"Tala Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Siham Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Shafik{Zuheir} Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"May Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Diana Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Inaam Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Jeryes Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Mona Khyou Saleh"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Rozan Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Najwan Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Merna Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Amal Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Tamer Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Josef Mazzawi"},
{ pre:"sLsLsLsLsLss"  , txt:"+Nabila Danial Awni"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Nabil Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Rami(Elias) Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Basel Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Abdallah Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Ms. Unknown"},
{ pre:"sLsLsLsLsLsB"  , txt:"Samuel Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Sawsan Semaan Hanna"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Jolie Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Jassica Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Joanna Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Loura Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Nabeel Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Nuha Rezik Assad"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Rimon Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Bassam Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Husam Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Kamal Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Afefeh Jeryes Mousa"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Rula Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Reem Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Lee Anne Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Abdallah Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Kamel Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Aziz Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Georgette Ghrayeb  Elias"},
{ pre:"sLsLsLsLsLsB"  , txt:"Suheir Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Shawki Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Amal Danial Fayez"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Aziz Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Fatin Hamati Bshara"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Shawki Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Osama Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Maroun Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Alaa Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Henry Mazzawi"},
{ pre:"sLsLsLsLsLss"  , txt:"+Aleki Matar Fuad"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Waseem Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Wesam Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Christin Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Shadi Mazzawi"},
{ pre:"sLsLsLsLsLsssB"  , txt:"Nermin Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Hana Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Raji Mazzawi"},
{ pre:"sLsLsLsL"  , txt:"+Olga Marche Yuseph"},
{ pre:"sLsLsLsLsB"  , txt:"Fairuz Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Ursula Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Marcelle Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Gabi Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Samira Drakebly  George"},
{ pre:"sLsLsLsLsLsB"  , txt:"Raji Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Coca Unknown"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Salma Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Samira Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Randa Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Jihad Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Madina Unknown"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Gabrielle Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Elias (Elie) Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Fouad Mazzawi"},
{ pre:"sLsLsLsLss"  , txt:"+Rosette Hawila"},
{ pre:"sLsLsLsLsssB"  , txt:"Fadi Mazzawi"},
{ pre:"sLsLsLsLsssL"  , txt:"+Yordanka Banal Mmoliner"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Yasmine Mazzawi"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Jason Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Hadi Mazzawi"},
{ pre:"sLsLsLsLsssL"  , txt:"+Lina Nakhoul"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Charbel Mazzawi"},
{ pre:"sLsLsLsLsssLsB"  , txt:"Rita Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Grace Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Olga Mazzawi"},
{ pre:"sLsLsLsLsssB"  , txt:"Rene Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Zahiya Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Najib Mazzawi"},
{ pre:"sLsLsLsL"  , txt:"+Maryam Karam Anton"},
{ pre:"sLsLsLsLsB"  , txt:"George Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+1) Nazira Nicola Mazzawi 2) Alexandra Makario"},
{ pre:"sLsLsLsLsLsB"  , txt:"Nelly Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Najib Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Nahi Shaer  Saeed"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Manal Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"George Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Nabil Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Suad Abd Elnur  Sael"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Nazira Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Lina Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Rita Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Essam Mazzawi"},
{ pre:"sLsLsLsLsLsLsL"  , txt:"+Jannette Mazzawi Naseef"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Rain Mazzawi"},
{ pre:"sLsLsLsLsLsLsLsB"  , txt:"Tia Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Shadi Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Andre Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Samir Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Mary Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Hilda Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Suad Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Amira Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Samira Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Georgette Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Fairouz Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Thuraya Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Naeem Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Nicola Mazzawi"},
{ pre:"sLsLsLsL"  , txt:"+Salma Yunes"},
{ pre:"sLsLsLsLsB"  , txt:"Rojina Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Hajaleh Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Arab Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Marcelle Mazzawi Raji"},
{ pre:"sLsLsLsLsLsB"  , txt:"Nicola Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Endera Mazzawi  Fawzi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Arab Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"John Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Marcelle Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Salma Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Nadera Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Sawsan Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Kheir Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Reem Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Nazirah Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Nassif Mazzawi"},
{ pre:"sLsLsLsL"  , txt:"+Shafika Helo Mubarak"},
{ pre:"sLsLsLsLsB"  , txt:"Zidan Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Ms. Souri"},
{ pre:"sLsLsLsLsLsB"  , txt:"Nassif Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Alissar Mazzawi Sami"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Zidan Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Janette Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Sami Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Wasseem Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Bishara Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Elia Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Jihan Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Samia Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"May Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Sabah Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Suheir Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Sami Mazzawi"},
{ pre:"sLsLsLsLsL"  , txt:"+Jandarc Helou Elias"},
{ pre:"sLsLsLsLsLsB"  , txt:"Samih Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Victor Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Elias Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Alissar Mazzawi"},
{ pre:"sLsLsLsLsLsL"  , txt:"+Nassif Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Zedan Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Janette Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Samir Mazzawi"},
{ pre:"sLsLsLsLsLsLsB"  , txt:"Wasim Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Katereen Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Samia Mazzawi"},
{ pre:"sLsLsLsLsLsB"  , txt:"Jiana Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Fayez Mazzawi"},
{ pre:"sLsLsLsLsB"  , txt:"Samih Mazzawi"},
{ pre:"sLsLsLsB"  , txt:"Said Mazzawi"},
{ pre:"sLsLsLss"  , txt:"+Thourya Zaher Shibly"},
{ pre:"sLsLsLsssB"  , txt:"Joul Mazzawi"},
{ pre:"sLsLsLsssL"  , txt:"+Ms. Unknown"},
{ pre:"sLsLsLsssLsB"  , txt:"Said(Joe) Mazzawi"},
{ pre:"sLsLsLsssLsB"  , txt:"Roni Mazzawi"},
{ pre:"sLsLsLsssLsB"  , txt:"Gladis Mazzawi"},
{ pre:"sLsLsLsssB"  , txt:"Juliette Mazzawi"},
{ pre:"sLsLsLsssB"  , txt:"Elias Mazzawi"},
{ pre:"sLsLsLsssL"  , txt:"+Ms. Unknown"},
{ pre:"sLsLsLsssLsB"  , txt:"Suheil Mazzawi"},
{ pre:"sLsLsLsssLsB"  , txt:"Diana Mazzawi"},
{ pre:"sLsLsLsssB"  , txt:"Emil Mazzawi"},
{ pre:"sLsLsLsssL"  , txt:"+Ms. Unknown"},
{ pre:"sLsLsLsssLsB"  , txt:"Nimer Mazzawi"},
{ pre:"sLsLsLsssLsB"  , txt:"Tina Mazzawi"},
{ pre:"sLsLsLsssB"  , txt:"Abla Mazzawi"},
{ pre:"sLsLsLsssB"  , txt:"Layla Mazzawi"},
{ pre:"sLsLsLsssB"  , txt:"Ayda Mazzawi"},
{ pre:"sLsLsB"  , txt:"Jeryes Mazzawi"},
{ pre:"sLsLss"  , txt:"+Afifeh Khoury"},
{ pre:"sLsLsssB"  , txt:"Khalil Mazzawi"},
{ pre:"sLsLsssB"  , txt:"Mateel Mazzawi"},
{ pre:"sLsLsssB"  , txt:"Fadeel Mazzawi"},
{ pre:"sLsLsssL"  , txt:"+Thurya Abu Salem Tannous"},
{ pre:"sLsLsssLsB"  , txt:"Afifi Mazzawi"},
{ pre:"sLsLsssLsB"  , txt:"Jeryes Mazzawi"},
{ pre:"sLsLsssLsL"  , txt:"+Vickie Issac Yako"},
{ pre:"sLsLsssLsLsB"  , txt:"Fadeel Mazzawi"},
{ pre:"sLsLsssLsLsB"  , txt:"Chris Mazzawi"},
{ pre:"sLsLsssLsLsB"  , txt:"Anthony Mazzawi"},
{ pre:"sLsLsssLsB"  , txt:"Tawfik Mazzawi"},
{ pre:"sLsLsssLss"  , txt:"+Ms. Unknown"},
{ pre:"sLsLsssLsssB"  , txt:"Nabil Mazzawi"},
{ pre:"sLsLsssB"  , txt:"Malakeh Mazzawi"},
{ pre:"sLsLsssB"  , txt:"Fadel Mazzawi"},
{ pre:"sLsLsssB"  , txt:"Fadoul Mazzawi"},
{ pre:"sLsLssss"  , txt:"+Latefeh Matar Yacoub"},
{ pre:"sLsLsssssB"  , txt:"Diab Mazzawi"},
{ pre:"sLsLsssssL"  , txt:"+Mary Nseir Sleiman"},
{ pre:"sLsLsssssLsB"  , txt:"George Mazzawi"},
{ pre:"sLsLsssssLss"  , txt:"+Suha Zaatre Fransice"},
{ pre:"sLsLsssssLsssB"  , txt:"Maria Mazzawi"},
{ pre:"sLsLsssssLsssB"  , txt:"Diab Mazzawi"},
{ pre:"sLsLsssssLsssB"  , txt:"Ragd Mazzawi"},
{ pre:"sLsLsssssB"  , txt:"Afif Mazzawi"},
{ pre:"sLsLsssssL"  , txt:"+Ms. Unknown"},
{ pre:"sLsLsssssLsB"  , txt:"Edward Mazzawi"},
{ pre:"sLsLsssssLsL"  , txt:"+Abeer Shurush Husni"},
{ pre:"sLsLsssssLsLsB"  , txt:"Afif Mazzawi"},
{ pre:"sLsLsssssLsLsB"  , txt:"Samer Mazzawi"},
{ pre:"sLsLsssssLsLsB"  , txt:"Jean Mazzawi"},
{ pre:"sLsLsssssLsB"  , txt:"Hani Mazzawi"},
{ pre:"sLsLsssssLsB"  , txt:"Sawsan Mazzawi"},
{ pre:"sLsLsssssLsB"  , txt:"Samir Mazzawi"},
{ pre:"sLsLsssssLsB"  , txt:"Maher Mazzawi"},
{ pre:"sLsLsssssLsL"  , txt:"+Amira Khoury Farid"},
{ pre:"sLsLsssssLsLsB"  , txt:"Lana Mazzawi"},
{ pre:"sLsLsssssLsLsB"  , txt:"Liyan Mazzawi"},
{ pre:"sLsLsssssLsLsB"  , txt:"Luzian Mazzawi"},
{ pre:"sLsLsssssLsB"  , txt:"Muna Mazzawi"},
{ pre:"sLsLsssssLsB"  , txt:"Fadoul Mazzawi"},
{ pre:"sLsLsssssLss"  , txt:"+Suzanne Kazmouz  George"},
{ pre:"sLsLsssssLsssB"  , txt:"Yasmeen Mazzawi"},
{ pre:"sLsLsssssLsssB"  , txt:"Rani Mazzawi"},
{ pre:"sLsLsssssLsssB"  , txt:"Nataly Mazzawi"},
{ pre:"sLsLsssssB"  , txt:"Fawzi Mazzawi"},
{ pre:"sLsLsssssL"  , txt:"+Camilia Qupty Hanna"},
{ pre:"sLsLsssssLsB"  , txt:"Samir Mazzawi"},
{ pre:"sLsLsssssLsL"  , txt:"+Reem Rizik Jamil"},
{ pre:"sLsLsssssLsLsB"  , txt:"Fawzi Mazzawi"},
{ pre:"sLsLsssssLsLsB"  , txt:"Majd Mazzawi"},
{ pre:"sLsLsssssLsLsB"  , txt:"Ward Mazzawi"},
{ pre:"sLsLsssssLsB"  , txt:"Suheil Mazzawi"},
{ pre:"sLsLsssssLsL"  , txt:"+Enaya Kattoura Louis"},
{ pre:"sLsLsssssLsLsB"  , txt:"Camilia Mazzawi"},
{ pre:"sLsLsssssLsLsB"  , txt:"Rabea Mazzawi"},
{ pre:"sLsLsssssLsB"  , txt:"Sahar Mazzawi"},
{ pre:"sLsLsssssLsB"  , txt:"Suzane Mazzawi"},
{ pre:"sLsLsssssLsB"  , txt:"Lubna Mazzawi"},
{ pre:"sLsLsssssLsB"  , txt:"Fifi Mazzawi"},
{ pre:"sLsLsssssB"  , txt:"Thouraya Mazzawi"},
{ pre:"sLsB"  , txt:"Wardeh Mazzawi"},
{ pre:"sLsB"  , txt:"Khazneh Mazzawi"},
{ pre:"sB"  , txt:"Moussa Mazzawi"},
{ pre:"ss"  , txt:"+Ms. Unknown"},
{ pre:"sssB"  , txt:"Ibrahim Mazzawi"},
{ pre:"sssB"  , txt:"Hilaneh Mazzawi"},
{ pre:"sssB"  , txt:"Mariam Mazzawi"},
{ pre:"sssB"  , txt:"Dahoud Mazzawi"},
{ pre:"sssL"  , txt:"+Takla Sawaf"},
{ pre:"sssLsB"  , txt:"Sleiman Mazzawi"},
{ pre:"sssLsL"  , txt:"+Wardeh Ghoros Yacoub"},
{ pre:"sssLsLsB"  , txt:"Elias Mazzawi"},
{ pre:"sssLsLsL"  , txt:"+Adlah Hawila  Yussef"},
{ pre:"sssLsLsLsB"  , txt:"Nazirah Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Marie Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Wadeaa Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Sadika Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Deeb Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Adeeb Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Nimer Mazzawi"},
{ pre:"sssLsLsLss"  , txt:"+Ms. Unknown"},
{ pre:"sssLsLsLsssB"  , txt:"Adeeb Mazzawi"},
{ pre:"sssLsLsLsssL"  , txt:"+Zuha Totary Elias"},
{ pre:"sssLsLsLsssLsB"  , txt:"Johnny (Hanna) Mazzawi"},
{ pre:"sssLsLsLsssLsL"  , txt:"+Samar Hadad Nabil"},
{ pre:"sssLsLsLsssLsLsB"  , txt:"Adeeb Mazzawi"},
{ pre:"sssLsLsLsssLsB"  , txt:"Marlene Mazzawi"},
{ pre:"sssLsLsLsssLsB"  , txt:"Bishara Mazzawi"},
{ pre:"sssLsLsLsssLss"  , txt:"+Brenda Adolfo Vazquez"},
{ pre:"sssLsLsLsssLsssB"  , txt:"Pierre Mazzawi"},
{ pre:"sssLsLsLsssB"  , txt:"Elias Mazzawi"},
{ pre:"sssLsLsLsssL"  , txt:"+Raghida Grayeb George"},
{ pre:"sssLsLsLsssLsB"  , txt:"Nimer Mazzawi"},
{ pre:"sssLsLsLsssLsB"  , txt:"Gladis Mazzawi"},
{ pre:"sssLsLsLsssLsB"  , txt:"Marianna Mazzawi"},
{ pre:"sssLsLsLsssB"  , txt:"Therese Mazzawi"},
{ pre:"sssLsLsLsssB"  , txt:"Gabi Mazzawi"},
{ pre:"sssLsLsLsssL"  , txt:"+Fadwa Mazzawi Saeed"},
{ pre:"sssLsLsLsssLsB"  , txt:"Tanios Mazzawi"},
{ pre:"sssLsLsLsssLsB"  , txt:"Marios Mazzawi"},
{ pre:"sssLsLsLsssB"  , txt:"Suzette Mazzawi"},
{ pre:"sssLsLsLsssB"  , txt:"Janette Mazzawi"},
{ pre:"sssLsLsLsssB"  , txt:"Edwar Mazzawi"},
{ pre:"sssLsLsLsssL"  , txt:"+Sawsan Maalouf Fahed"},
{ pre:"sssLsLsLsssLsB"  , txt:"Menerva Mazzawi"},
{ pre:"sssLsLsLsssLsB"  , txt:"Shadi Mazzawi"},
{ pre:"sssLsLsLsssLsB"  , txt:"Alhan Mazzawi"},
{ pre:"sssLsLsLsssB"  , txt:"Zuher Mazzawi"},
{ pre:"sssLsLsLsssL"  , txt:"+Hind Qupty Faraj"},
{ pre:"sssLsLsLsssLsB"  , txt:"Fairuz Mazzawi"},
{ pre:"sssLsLsLsssLsB"  , txt:"Venus Mazzawi"},
{ pre:"sssLsLsLsssLsB"  , txt:"Vivian Mazzawi"},
{ pre:"sssLsLsLsssLsB"  , txt:"Firas Mazzawi"},
{ pre:"sssLsLsLsssB"  , txt:"Kawthar Mazzawi"},
{ pre:"sssLsLsLsssB"  , txt:"Katerina Mazzawi"},
{ pre:"sssLsLsB"  , txt:"Nazha Mazzawi"},
{ pre:"sssLsLsB"  , txt:"Abdou Mazzawi"},
{ pre:"sssLsLsL"  , txt:"+Labebeh Mazzawi  Elias"},
{ pre:"sssLsLsLsB"  , txt:"Fadwa Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Saleema Mazzawi"},
{ pre:"sssLsLsB"  , txt:"Dahoud Mazzawi"},
{ pre:"sssLsLsL"  , txt:"+Adlah Sruji  Saleem"},
{ pre:"sssLsLsLsB"  , txt:"Warda Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Nazha Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Abdallah Mazzawi"},
{ pre:"sssLsLsLsL"  , txt:"+Salwa Nakhle  Nasri"},
{ pre:"sssLsLsLsLsB"  , txt:"Mary Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Dahoud Mazzawi"},
{ pre:"sssLsLsLsLsL"  , txt:"+Bahia Far Subhi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Juwanna Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Abdallah Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Mario Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Lucy Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Yuseph Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Sleiman Mazzawi"},
{ pre:"sssLsLsLsL"  , txt:"+Rose Bagtasar Zaki"},
{ pre:"sssLsLsLsLsB"  , txt:"Yuseph Mazzawi"},
{ pre:"sssLsLsLsLsL"  , txt:"+Marcelle Musa George"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Sirin Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Sintia Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Sleiman Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Eva Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Ghada Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Raghida Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Azmi Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Sami Mazzawi"},
{ pre:"sssLsLsLss"  , txt:"+Hilane Eilabouny  Jeryes"},
{ pre:"sssLsLsLsssB"  , txt:"Hani Mazzawi"},
{ pre:"sssLsLsLsssL"  , txt:"+Rabab Bisharat Elias"},
{ pre:"sssLsLsLsssLsB"  , txt:"Saly Mazzawi"},
{ pre:"sssLsLsLsssLsB"  , txt:"Samir Mazzawi"},
{ pre:"sssLsLsLsssLsB"  , txt:"Saher Mazzawi"},
{ pre:"sssLsLsLsssB"  , txt:"Halla Mazzawi"},
{ pre:"sssLsLsLsssB"  , txt:"Adela Mazzawi"},
{ pre:"sssLsLsLsssB"  , txt:"Adel Mazzawi"},
{ pre:"sssLsLsLsssL"  , txt:"+Muna Bisharat Elias"},
{ pre:"sssLsLsLsssLsB"  , txt:"Dona Mazzawi"},
{ pre:"sssLsLsLsssLsB"  , txt:"Jiries Mazzawi"},
{ pre:"sssLsLsLsssB"  , txt:"Fatina Mazzawi"},
{ pre:"sssLsLsLsssB"  , txt:"Naela Mazzawi"},
{ pre:"sssLsLsB"  , txt:"Asaad Mazzawi"},
{ pre:"sssLsLsB"  , txt:"Adlah Mazzawi"},
{ pre:"sssLsLsB"  , txt:"Gerges Mazzawi"},
{ pre:"sssLsLsssB"  , txt:"Yuseph Mazzawi"},
{ pre:"sssLsLsssB"  , txt:"Alees Mazzawi"},
{ pre:"sssLsLsssB"  , txt:"Asaad Mazzawi"},
{ pre:"sssLsLsssB"  , txt:"George Mazzawi"},
{ pre:"sssLsLsssB"  , txt:"Marie Mazzawi"},
{ pre:"sssLsLsssB"  , txt:"Yassou Mazzawi"},
{ pre:"sssLsB"  , txt:"Yousef Mazzawi"},
{ pre:"sssLsL"  , txt:"+Saadah Matta Elias"},
{ pre:"sssLsLsB"  , txt:"Farha Mazzawi"},
{ pre:"sssLsLsB"  , txt:"Jemeela Mazzawi"},
{ pre:"sssLsLsB"  , txt:"Salim Mazzawi"},
{ pre:"sssLsLss"  , txt:"+Adlah Mazzawi  Sleiman"},
{ pre:"sssLsLsssB"  , txt:"Yousef Mazzawi"},
{ pre:"sssLsLssss"  , txt:"+Labibeh Mazzawi"},
{ pre:"sssLsLsssssB"  , txt:"Salim Mazzawi"},
{ pre:"sssLsLsssssL"  , txt:"+Louisa Hawa Hanna"},
{ pre:"sssLsLsssssLsB"  , txt:"Yuseph Mazzawi"},
{ pre:"sssLsLsssssLsB"  , txt:"Grace Mazzawi"},
{ pre:"sssLsLsssssLsB"  , txt:"Jessy Mazzawi"},
{ pre:"sssLsLsssssB"  , txt:"Jeryes Mazzawi"},
{ pre:"sssLsLsssssL"  , txt:"+Wafa Abu Helou Yacob"},
{ pre:"sssLsLsssssLsB"  , txt:"Sylvia Mazzawi"},
{ pre:"sssLsLsssssLsB"  , txt:"Ashraf Mazzawi"},
{ pre:"sssLsLsssssLsB"  , txt:"Cezar Mazzawi"},
{ pre:"sssLsLsssssB"  , txt:"Suheil Mazzawi"},
{ pre:"sssLsLsssssL"  , txt:"+Amal Hamam Hanna"},
{ pre:"sssLsLsssssLsB"  , txt:"Shady Mazzawi"},
{ pre:"sssLsLsssssLsB"  , txt:"Ameer Mazzawi"},
{ pre:"sssLsLsssssLsB"  , txt:"Sereen Mazzawi"},
{ pre:"sssLsLsssssB"  , txt:"Sawsan Mazzawi"},
{ pre:"sssLsB"  , txt:"Ibrahim Mazzawi"},
{ pre:"sssLsL"  , txt:"+Martha Assileh Yuseph"},
{ pre:"sssLsLsB"  , txt:"Warda Mazzawi"},
{ pre:"sssLsLsB"  , txt:"Afifeh Mazzawi"},
{ pre:"sssLsLsB"  , txt:"Jeryes Mazzawi"},
{ pre:"sssLsLsL"  , txt:"+Rafia Abu Raed  Yussef"},
{ pre:"sssLsLsLsB"  , txt:"Marie Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Jameel Mazzawi"},
{ pre:"sssLsLsLsL"  , txt:"+Agnees Unknown"},
{ pre:"sssLsLsLsLsB"  , txt:"Marwan Mazzawi"},
{ pre:"sssLsLsLsLsL"  , txt:"+Jenevief Dbyat Fadool"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Jameel Mazzawi"},
{ pre:"sssLsLsLsLsLsL"  , txt:"+Ms. Unknown"},
{ pre:"sssLsLsLsLsLsLsB"  , txt:"Tala Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Ameer Mazzawi"},
{ pre:"sssLsLsLsLsLsL"  , txt:"+Rozalin ---- Neameh"},
{ pre:"sssLsLsLsLsLsLsB"  , txt:"Juliette Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Shereen Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Areen Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Akram Mazzawi"},
{ pre:"sssLsLsLsLsL"  , txt:"+Mary Elias Raja"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Hisham Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Agnees Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Azmi Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Amal Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Ahlam Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Eman Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Afifeh Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Afif Mazzawi"},
{ pre:"sssLsLsLsL"  , txt:"+Therese Sibani  Tawfik"},
{ pre:"sssLsLsLsLsB"  , txt:"George Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"William Mazzawi"},
{ pre:"sssLsLsLsLsL"  , txt:"+Claire Shammas Nimer"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Waseem Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Maryan Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Shada Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Katy Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Roni Mazzawi"},
{ pre:"sssLsLsLsLss"  , txt:"+Baseema Jabaly Yuseph"},
{ pre:"sssLsLsLsLsssB"  , txt:"Duna Mazzawi"},
{ pre:"sssLsLsLsLsssB"  , txt:"Layal Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Salwa Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Samih Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Marcelle Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Layla Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Therese Mazzawi"},
{ pre:"sssLsLsB"  , txt:"Farideh Mazzawi"},
{ pre:"sssLsB"  , txt:"Iseed Mazzawi"},
{ pre:"sssLsL"  , txt:"+Saadah Abawi"},
{ pre:"sssLsLsB"  , txt:"Jarmas Mazzawi"},
{ pre:"sssLsLsL"  , txt:"+Saleemeh Mazzawi  Abdou"},
{ pre:"sssLsLsLsB"  , txt:"Iseed Mazzawi"},
{ pre:"sssLsLsLsL"  , txt:"+Aniseh Espanioly Salim"},
{ pre:"sssLsLsLsLsB"  , txt:"George Mazzawi"},
{ pre:"sssLsLsLsLsL"  , txt:"+Elham Unknown"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Nancy Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Iseed Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Rami Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Venice Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Jihad Mazzawi"},
{ pre:"sssLsLsLsLsL"  , txt:"+Samiha Unknown"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Robert Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Roger Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Riyad Mazzawi"},
{ pre:"sssLsLsLsLsL"  , txt:"+Amira Unknown"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Elie Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Elianne Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Rosanne Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Fadwa Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Ziad Mazzawi"},
{ pre:"sssLsLsLsLsL"  , txt:"+Ms. Unknown"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Lina Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Pierre Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Rana Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Marlene Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Bishara Mazzawi"},
{ pre:"sssLsLsLsL"  , txt:"+1) Azize Sbete 2)victoria Dagher Farid"},
{ pre:"sssLsLsLsLsB"  , txt:"Tanios Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Victor Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Ghassan Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Rita Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Ghada Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Abdou Mazzawi"},
{ pre:"sssLsLsLsL"  , txt:"+Nahi Mourani Nayef"},
{ pre:"sssLsLsLsLsB"  , txt:"Antoinette Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Tony Mazzawi"},
{ pre:"sssLsLsLsLsL"  , txt:"+Yvette Khalil Saliba"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Nahi Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Abdou Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Jarmas Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Mr. Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Medhat Mazzawi"},
{ pre:"sssLsLsLsLsL"  , txt:"+Rula Mkaabal Edwar"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Shadi Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Madona Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Juan Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Maher Mazzawi"},
{ pre:"sssLsLsLsLsL"  , txt:"+Elana Rinawi George"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Marina Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Mikhaeel Mazzawi"},
{ pre:"sssLsLsLsLsLsB"  , txt:"Chris Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Nisreen Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Shereen Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Jackleen Mazzawi"},
{ pre:"sssLsLsLsLsB"  , txt:"Samer Mazzawi"},
{ pre:"sssLsLsLsLss"  , txt:"+Wafaa Helou Farid"},
{ pre:"sssLsLsLsLsssB"  , txt:"George Mazzawi"},
{ pre:"sssLsLsLsLsssB"  , txt:"Jowel Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Diyaa Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Hajaleh Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Labibeh Mazzawi"},
{ pre:"sssLsLsLsB"  , txt:"Georgette Mazzawi"},
{ pre:"sssLsLsB"  , txt:"Najlaa Mazzawi"},
{ pre:"sssLsB"  , txt:"Khalil Mazzawi"},
{ pre:"sssLsL"  , txt:"+Hanneh Mazzawi Nasser"},
{ pre:"sssLsLsB"  , txt:"Marta Mazzawi"},
{ pre:"sssLsLsB"  , txt:"Radiyeh Mazzawi"},
{ pre:"sssLsLsB"  , txt:"Radi Mazzawi"},
{ pre:"sssLsLsL"  , txt:"+Nazha Mazzawi  Sleiman"},
{ pre:"sssLsLsLsB"  , txt:"Khalil Mazzawi"},
{ pre:"sssLsLsB"  , txt:"Maryam Mazzawi"},
{ pre:"sssLsLsB"  , txt:"Khalil Mazzawi"},
{ pre:"sssLsB"  , txt:"Nasrah Mazzawi"},
{ pre:"sssB"  , txt:"Yousef Mazzawi"},
{ pre:"ssss"  , txt:"+Martha Zahlan"},
{ pre:"sssssB"  , txt:"Elias Mazzawi"},
{ pre:"sssssL"  , txt:"+Saadah Marche Yuseph"},
{ pre:"sssssLsB"  , txt:"Yousef Mazzawi"},
{ pre:"sssssLsB"  , txt:"Salim Mazzawi"},
{ pre:"sssssLsB"  , txt:"Labibah Mazzawi"},
{ pre:"sssssLsB"  , txt:"Boulos Mazzawi"},
{ pre:"sssssLsL"  , txt:"+Ms. Unknown"},
{ pre:"sssssLsLsB"  , txt:"Maryam Mazzawi"},
{ pre:"sssssLsB"  , txt:"Boutrus Mazzawi"},
{ pre:"sssssB"  , txt:"Moussa Mazzawi"},
{ pre:"sssssL"  , txt:"+Khazneh Sruji  Elias"},
{ pre:"sssssLsB"  , txt:"Tawfik Mazzawi"},
{ pre:"sssssLsL"  , txt:"+Bahya Tabry Ibrahim"},
{ pre:"sssssLsLsB"  , txt:"Botrous Mazzawi"},
{ pre:"sssssLsLsB"  , txt:"Mubadda Mazzawi"},
{ pre:"sssssLsLsB"  , txt:"Fadwa Mazzawi"},
{ pre:"sssssLsLsB"  , txt:"Aziz Mazzawi"},
{ pre:"sssssLsLsL"  , txt:"+Evelyne Asfour"},
{ pre:"sssssLsLsLsB"  , txt:"Nabil Mazzawi"},
{ pre:"sssssLsLsLsL"  , txt:"+Randa Bajjali"},
{ pre:"sssssLsLsLsLsB"  , txt:"Aziz Mazzawi"},
{ pre:"sssssLsLsLsLsB"  , txt:"Ziad Mazzawi"},
{ pre:"sssssLsLsLsB"  , txt:"Norma Mazzawi"},
{ pre:"sssssLsLsLsB"  , txt:"Bahaa Mazzawi"},
{ pre:"sssssLsLsB"  , txt:"Yousef Mazzawi"},
{ pre:"sssssLsLsL"  , txt:"+Abla Halyus Naser"},
{ pre:"sssssLsLsLsB"  , txt:"Evette Mazzawi"},
{ pre:"sssssLsLsLsB"  , txt:"Randa Mazzawi"},
{ pre:"sssssLsLsLsB"  , txt:"Simon Mazzawi"},
{ pre:"sssssLsLsLsL"  , txt:"+Suheila Khoury Fayez"},
{ pre:"sssssLsLsLsLsB"  , txt:"Yusef Mazzawi"},
{ pre:"sssssLsLsLsLsB"  , txt:"Kareen Mazzawi"},
{ pre:"sssssLsLsLsLsB"  , txt:"Elias Mazzawi"},
{ pre:"sssssLsLsLsB"  , txt:"Rimon Mazzawi"},
{ pre:"sssssLsLsLsL"  , txt:"+Alice Abu Shkara Farid"},
{ pre:"sssssLsLsLsLsB"  , txt:"Julian Mazzawi"},
{ pre:"sssssLsLsLsLsB"  , txt:"Maya Mazzawi"},
{ pre:"sssssLsLsLsLsB"  , txt:"Joy Mazzawi"},
{ pre:"sssssLsLsLsB"  , txt:"Tony Mazzawi"},
{ pre:"sssssLsLsLsL"  , txt:"+Samia Khoury Marjieh Zuheir"},
{ pre:"sssssLsLsLsLsB"  , txt:"Alber Mazzawi"},
{ pre:"sssssLsLsLsLsB"  , txt:"Elyana Mazzawi"},
{ pre:"sssssLsLsLsLsB"  , txt:"Nataly Mazzawi"},
{ pre:"sssssLsLsLsB"  , txt:"Bahaa Mazzawi"},
{ pre:"sssssLsLsLsB"  , txt:"Linda Mazzawi"},
{ pre:"sssssLsLsB"  , txt:"Rafia Mazzawi"},
{ pre:"sssssLsLsB"  , txt:"Hanna Mazzawi"},
{ pre:"sssssLsLss"  , txt:"+Shafiah Unknown"},
{ pre:"sssssLsLsssB"  , txt:"Tawfik Mazzawi"},
{ pre:"sssssLsLsssL"  , txt:"+Mary Helou Michel"},
{ pre:"sssssLsLsssLsB"  , txt:"Luzian Mazzawi"},
{ pre:"sssssLsLsssLsB"  , txt:"Hanna Mazzawi"},
{ pre:"sssssLsLsssLsB"  , txt:"Ehab Mazzawi"},
{ pre:"sssssLsLsssB"  , txt:"Fouad Mazzawi"},
{ pre:"sssssLsLsssL"  , txt:"+Ms. Mazat"},
{ pre:"sssssLsLsssLsB"  , txt:"Fadia Mazzawi"},
{ pre:"sssssLsLsssB"  , txt:"Samir Mazzawi"},
{ pre:"sssssLsLssss"  , txt:"+Fadya Helou  Jeryes"},
{ pre:"sssssLsLsssssB"  , txt:"Areen Mazzawi"},
{ pre:"sssssLsLsssssB"  , txt:"Emad Mazzawi"},
{ pre:"sssssLsLsssssB"  , txt:"Mirail Mazzawi"},
{ pre:"sssssLsB"  , txt:"Adlah Mazzawi"},
{ pre:"sssssLsB"  , txt:"Nazeerah Mazzawi"},
{ pre:"sssssLsB"  , txt:"Maryam Mazzawi"},
{ pre:"sssssLsB"  , txt:"Mateel Mazzawi"},
{ pre:"sssssLsB"  , txt:"Jameeleh Mazzawi"},
{ pre:"sssssLsB"  , txt:"Marta Mazzawi"},
{ pre:"sssssLsB"  , txt:"Elias Mazzawi"},
{ pre:"sssssLss"  , txt:"+Fahdeh Unknown"},
{ pre:"sssssLsssB"  , txt:"Shafika Mazzawi"},
{ pre:"sssssLsssB"  , txt:"Moussa Mazzawi"},
{ pre:"sssssLsssB"  , txt:"Marie Mazzawi"},
{ pre:"sssssLsssB"  , txt:"Shafik Mazzawi"},
{ pre:"sssssLsssL"  , txt:"+Samia Unknown"},
{ pre:"sssssLsssLsB"  , txt:"Nibal Mazzawi"},
{ pre:"sssssLsssLsB"  , txt:"Eman Mazzawi"},
{ pre:"sssssLsssLsB"  , txt:"Sawsan Mazzawi"},
{ pre:"sssssLsssLsB"  , txt:"Manal Mazzawi"},
{ pre:"sssssLsssLsB"  , txt:"Fadi Mazzawi"},
{ pre:"sssssLsssB"  , txt:"Menerva Mazzawi"},
{ pre:"sssssLsssB"  , txt:"Muzayan Mazzawi"},
{ pre:"sssssB"  , txt:"Saada Mazzawi"},
{ pre:"sssssB"  , txt:"Nijmeh Mazzawi"},
{ pre:"sssssB"  , txt:"Helaneh Mazzawi"},
{ pre:"sssssB"  , txt:"Saadah Mazzawi"},
{ pre: "" , txt: "" } // dummy row // note that there are ~ 1360 total family members [~ number of rows] since the 1st ancestor !
];